import { SvelteMap } from 'svelte/reactivity';
import { preview, guiState, proxyConfigSignal } from './state.svelte';
const toasts = new SvelteMap();
export const getToasts = () => toasts;
export const dismissToast = () => {};
export const success = (message: string) => { preview.feedback = message; };
export const error = success;
export const warning = success;
export const info = success;
export const getAppErrorMessage = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
export const getCorePolicies = async () => ({ groups: guiState.policyGroups });
export const getGuiCoreHealth = async () => ({ engineVersion: '0.0.16-rc.202609060636' });
export const getGuiStackStatus = async () => ({ key: 'systemStack', supported: true, enabled: true, state: 'running' });
export const getRuntimePerformanceSnapshot = async () => ({ core: { cpuPercent: 0.24, memoryBytes: 51000000 } });
export const detectKernelVersion = async () => ({ version: '0.0.16-rc.202609060636', executableExists: true });
export const listKernelVersions = async () => ({ versions: [] });
export const listSubscriptions = async () => [];
export const listProxyConfigs = async () => [{ id: 'demo', name: '日常网络' }, { id: 'work', name: '工作配置' }].map(item => ({ ...item, active: item.id === guiState.selfTest.activeProxyConfigId, format: 'zero', content: {} }));
export const setActiveProxyConfig = async (id: string) => { const result = await guiState.chooseProfile(id); if (!result?.ok) throw new Error(result?.message ?? '模拟切换失败'); proxyConfigSignal.markChanged(); return (await listProxyConfigs()).find(item => item.id === id)!; };
export const syncSubscription = async () => { preview.feedback = '模拟订阅同步完成'; };
export const showTrafficBall = async () => { preview.feedback = '此处为原客户端窗口操作，浏览器预览不执行'; };
