#!/usr/bin/env bash
# update_version.sh — Bump the project version across all manifest files,
# commit, tag, and push to every configured remote.
#
# Usage:   bash scripts/update_version.sh <version> [--force]
# Example: bash scripts/update_version.sh 0.1.0
#          bash scripts/update_version.sh 0.1.0 --force  # rebuild tag at HEAD
set -euo pipefail

# ── helpers ──────────────────────────────────────────────────────────────
die() { echo "ERROR: $*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: update_version.sh <version> [--force]

Without --force, bumps all manifests, commits, tags, and pushes every remote.
With --force, an already-current version skips the bump/commit, rebuilds its
annotated tag at the current HEAD, and force-updates that tag on every remote.
The force path requires a clean worktree.
EOF
}

# Validate semver shape: digits.digits.digits (optional -suffix)
is_valid_version() {
  [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.]+)?$ ]]
}

# ── guard ────────────────────────────────────────────────────────────────
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  die "missing version argument — usage: $0 <version> [--force]"
fi

shift
FORCE=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    --force|-f) FORCE=true ;;
    --help|-h) usage; exit 0 ;;
    *) die "unknown argument '$1' — usage: $0 <version> [--force]" ;;
  esac
  shift
done

if ! is_valid_version "$VERSION"; then
  die "invalid version '$VERSION' — expected semver, e.g. 0.1.0 or 0.1.0-beta.1"
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# ── discover manifest files that carry the version ───────────────────────
#
# We update four files:
#   1. package.json              — JS   "version": "..."
#   2. src-tauri/Cargo.toml      — Rust version = "..."
#   3. src-tauri/tauri.conf.json — Tauri "version": "..."
#   4. src-tauri/Cargo.lock      — regenerated by cargo (NOT sed; see below)
#
# 1-3 use a simple sed replacement.  Cargo.lock is regenerated by cargo
# after the Cargo.toml bump, because a blanket sed on version strings
# would also hit third-party crates whose version happens to match the
# project's old version.  The current version is read from package.json
# to avoid a hard-coded fallback.

CURRENT_VERSION=$(node -p "require('./package.json').version" 2>/dev/null) || \
  CURRENT_VERSION=$(grep '"version"' package.json | head -1 | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')

if [ -z "$CURRENT_VERSION" ]; then
  die "could not determine current version from package.json"
fi

RETAG_ONLY=false
if [ "$CURRENT_VERSION" = "$VERSION" ]; then
  if [ "$FORCE" != true ]; then
    die "version $VERSION is already the current version — use --force to rebuild and republish its tag"
  fi
  if [ -n "$(git status --porcelain)" ]; then
    die "--force requires a clean worktree before tagging the current HEAD"
  fi
  RETAG_ONLY=true
  echo "Version $VERSION is already current — rebuilding its tag at HEAD"
else
  if [ "$FORCE" = true ]; then
    die "--force only rebuilds the already-current version tag; omit it for a normal version bump"
  fi
  echo "Bumping $CURRENT_VERSION → $VERSION"
fi

# ── update files ─────────────────────────────────────────────────────────
# Use sed -i with a backup extension because macOS sed requires one.
# The backup is deleted immediately after a successful run.
do_sed() {
  local file="$1" pattern="$2"
  if [ ! -f "$file" ]; then
    die "expected manifest file not found: $file"
  fi
  sed -i.bak "$pattern" "$file" && rm -f "${file}.bak"
}

if [ "$RETAG_ONLY" != true ]; then
  do_sed "package.json" \
    "s/\"version\":[[:space:]]*\"$CURRENT_VERSION\"/\"version\": \"$VERSION\"/"

  do_sed "src-tauri/Cargo.toml" \
    "s/^version[[:space:]]*=[[:space:]]*\"$CURRENT_VERSION\"/version = \"$VERSION\"/"

  do_sed "src-tauri/tauri.conf.json" \
    "s/\"version\":[[:space:]]*\"$CURRENT_VERSION\"/\"version\": \"$VERSION\"/"

  # Do NOT sed Cargo.lock: it carries a `version` field for every transitive
  # dependency, and a blanket string replace corrupts any third-party crate
  # whose version happens to equal $CURRENT_VERSION (a prior bump rewrote
  # `dtor-proc-macro` 0.0.6 to 0.0.7-beta).  Let cargo regenerate the entry.
  echo "Syncing src-tauri/Cargo.lock via cargo…"
  cargo check --manifest-path src-tauri/Cargo.toml -q

  echo "Updated manifests:"
  echo "  package.json"
  echo "  src-tauri/Cargo.toml"
  echo "  src-tauri/Cargo.lock (via cargo)"
  echo "  src-tauri/tauri.conf.json"

  # ── commit ─────────────────────────────────────────────────────────────
  git add \
    package.json \
    src-tauri/Cargo.toml \
    src-tauri/Cargo.lock \
    src-tauri/tauri.conf.json

  COMMIT_MSG="chore(release): bump version to $VERSION"
  echo ""
  echo "Committing: $COMMIT_MSG"
  git commit -m "$COMMIT_MSG"
fi

TAG="v$VERSION"
if [ "$FORCE" = true ]; then
  echo "Force-tagging current HEAD: $TAG"
  git tag -fa "$TAG" -m "$TAG"
else
  echo "Tagging: $TAG"
  git tag -a "$TAG" -m "$TAG"
fi

# ── push to all remotes ──────────────────────────────────────────────────
REMOTES=$(git remote)
if [ -z "$REMOTES" ]; then
  die "no git remotes configured — cannot push"
fi

echo ""
BRANCH=$(git rev-parse --abbrev-ref HEAD)
for remote in $REMOTES; do
  echo "Pushing $BRANCH → $remote"
  git push "$remote" "$BRANCH"

  if [ "$FORCE" = true ]; then
    echo "Force-pushing tag $TAG → $remote"
    git push --force "$remote" "refs/tags/$TAG:refs/tags/$TAG"
  else
    echo "Pushing tag $TAG → $remote"
    git push "$remote" "$TAG"
  fi
done

echo ""
echo "Done — version $VERSION pushed to all remotes"
